version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:latest
    networks:
      - my-network

  producer:
    environment:
      - RABBIT_HOST_NAME=rabbitmq
      - RABBIT_QUEUE_NAME=worker_queue
    build: ./producer
    networks:
      - my-network

  consumer:
    environment:
      - RABBIT_HOST_NAME=rabbitmq
      - RABBIT_QUEUE_NAME=worker_queue
    build: ./consumer
    networks:
      - my-network

networks:
  my-network:
    driver: bridge